inherit_from: .rubocop_todo.yml

# Offense count: 43
# Cop supports --auto-correct.
# Configuration parameters: AutoCorrect, AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Layout/LineLength:
  Max: 151

# Offense count: 1
# Configuration parameters: CountComments, ExcludedMethods.
Metrics/MethodLength:
  Max: 19

# Offense count: 19
# Cop supports --auto-correct.
Style/PreferredHashMethods:
  Enabled: false

# Offense count: 9
# Cop supports --auto-correct.
Layout/FirstArrayElementIndentation:
  Enabled: false

# Offense count: 261
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Layout/FirstHashElementIndentation:
  Enabled: false
# Offense count: 5

# Cop supports --auto-correct.
Lint/RedundantStringCoercion:
  Enabled: false

# disabling a bunch of style linters
Layout/BlockAlignment:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Lint/Loop:
  Enabled: false

Lint/Void:
  Exclude:
    - dashboard/spec/**/*

Layout/AccessModifierIndentation:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Layout/ArrayAlignment:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false

Style/CollectionMethods:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Style/DefWithParentheses:
  Enabled: false

Layout/DotPosition:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Style/MultilineIfThen:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Style/NilComparison:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Layout/SpaceAfterComma:
  Enabled: false

Layout/SpaceAfterNot:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Layout/SpaceInsideParens:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/WhileUntilDo:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false

Layout/ClosingHeredocIndentation:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

# Things that are off but we should turn on eventually

Style/Next:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

####

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
